# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd402585791876bfc888f6c78d24d0d6ab2fb68caf4a3e27380e315b0470d8ea966f269f9e0c76164839511230b9c1e44b8634393e96247da135b0b4101eaba

test:
  secret_key_base: 2580ced868bf4c7a1740cfcce7817bdbe96c4d0341e06901f38b16a833db0c81cac06ba667543f54ff943aba0f5c9f7d58fc6d61081c20439faf9558a273ee8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
